import math
print('Scientific Calculator')
print()
a=int(input('Enter a '))
b=int(input('Enter b '))
print('a=',a)
print('b=',b)
print()
print('Arthematic Operations')
print('sum=',a+b)
print('sub=',a-b)
print('div=',a/b)
print('mul=',a*b)
print()
print('Exponential Operation')
print('power=',a**b)
print('Modulus=',a%b)
print()
print('Trignometric Opearation')
print('sin(3)=',math.sin(3))
print('sin(-3)=',math.sin(-3))
print('cos(3)=',math.cos(3))
print('cos(-3)=',math.cos(-3))
print('tan(3)=',math.tan(3))
print('tan(-3)=',math.tan(-3))

